### ISSUE TITLE
Upgrade to Django 1.7

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#1903]
We're currently on 1.4 and there are lots of good improvements to pick up.

**Comment by bendk** [comment]
One thing that I think will happen with this release is the session storage willl change.  This means users will need to re-log in to amara after the update.  This seems reasonable, but tell me if we should try to mitigate this.

**Comment by bendk** [comment]
Changed the title to 'upgrade to django 1.7'.  There are newer django versions, but I think this is a big enough jump that we should stop at 1.7, then upgrade more later.

**Comment by bendk** [comment]
Okay, this one is ready to be tested.  Bunch of notes here:

- To test, you need a new version of the amara docker image.  I think this is the best way to handle this:
  - From the current dev branch, run `docker tag amara-app:latest amara-app:dev`
  - Switch to the django-1.7 branch
  - Run `dev build`
  - Run `docker tag amara-app:latest amara-app:django-1.7`
  - From then on, you can swictch between the 2 docker images:
     - Run `docker tag amara-app:dev amara-app:latest`  to switch to the current version
     - Run `docker tag amara-app:django-1.7 amara-app:latest`  to switch to the new version
- One big thing to test is the database migrations, there are two cases here:
  - Creating a new DB with `dev dbreset`
  - Importing an DB from dev with `dev manage migrate --fake`
- For both of those, do a general smoke test to see that amara runs okay afterwards
- Do extra testing on the importing an old DB route -- this is how it's going to work on production.
- I wish I had a guide on what to test, but there's really not much specific.  Basically just do some general testing.

**Comment by PCF-Testing** [comment]
With a new db (dbreset), the following errors happen:

- [ ] Exception on the user profile page:

NoReverseMatch at /profiles/profile/maggie_s/
Reverse for 'auth_customuser_change' with arguments '(10001L,)' and keyword arguments '{}' not found. 0 pattern(s) tried: []
Request Method:	GET
Request URL:	http://unisubs.example.com:8000/en/profiles/profile/maggie_s/
Django Version:	1.7.11
Exception Type:	NoReverseMatch
Exception Value:	
Reverse for 'auth_customuser_change' with arguments '(10001L,)' and keyword arguments '{}' not found. 0 pattern(s) tried: []
Exception Location:	/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py in _reverse_with_prefix, line 468

Traceback:
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response
  111.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/opt/apps/amara/apps/profiles/views.py" in profile
  110.                        extra_context=extra_context)
File "/opt/apps/amara/utils/objectlist.py" in object_list
  57.     return render(request, template_name, context)
File "/usr/local/lib/python2.7/dist-packages/django/shortcuts.py" in render
  50.     return HttpResponse(loader.render_to_string(*args, **kwargs),
File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py" in render_to_string
  178.         return t.render(context_instance)
File "/usr/local/lib/python2.7/dist-packages/django/template/base.py" in render
  148.             return self._render(context)
File "/usr/local/lib/python2.7/dist-packages/django/template/base.py" in _render
  142.         return self.nodelist.render(context)
File "/usr/local/lib/python2.7/dist-packages/django/template/base.py" in render
  844.                 bit = self.render_node(node, context)
File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py" in render_node
  80.             return node.render(context)
File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py" in render
  126.         return compiled_parent._render(context)
File "/usr/local/lib/python2.7/dist-packages/django/template/base.py" in _render
  142.         return self.nodelist.render(context)
File "/usr/local/lib/python2.7/dist-packages/django/template/base.py" in render
  844.                 bit = self.render_node(node, context)
File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py" in render_node
  80.             return node.render(context)
File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py" in render
  126.         return compiled_parent._render(context)
File "/usr/local/lib/python2.7/dist-packages/django/template/base.py" in _render
  142.         return self.nodelist.render(context)
File "/usr/local/lib/python2.7/dist-packages/django/template/base.py" in render
  844.                 bit = self.render_node(node, context)
File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py" in render_node
  80.             return node.render(context)
File "/usr/local/lib/python2.7/dist-packages/django/template/defaulttags.py" in render
  312.                 return nodelist.render(context)
File "/usr/local/lib/python2.7/dist-packages/django/template/base.py" in render
  844.                 bit = self.render_node(node, context)
File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py" in render_node
  80.             return node.render(context)
File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py" in render
  65.                 result = block.nodelist.render(context)
File "/usr/local/lib/python2.7/dist-packages/django/template/base.py" in render
  844.                 bit = self.render_node(node, context)
File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py" in render_node
  80.             return node.render(context)
File "/usr/local/lib/python2.7/dist-packages/django/template/defaulttags.py" in render
  312.                 return nodelist.render(context)
File "/usr/local/lib/python2.7/dist-packages/django/template/base.py" in render
  844.                 bit = self.render_node(node, context)
File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py" in render_node
  80.             return node.render(context)
File "/usr/local/lib/python2.7/dist-packages/django/template/defaulttags.py" in render
  458.                         six.reraise(*exc_info)
File "/usr/local/lib/python2.7/dist-packages/django/template/defaulttags.py" in render
  444.             url = reverse(view_name, args=args, kwargs=kwargs, current_app=context.current_app)
File "/opt/apps/amara/apps/localeurl/__init__.py" in reverse
  18.             path = django_reverse(viewname, urlconf, args, kwargs, prefix, current_app)
File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py" in reverse
  551.     return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py" in _reverse_with_prefix
  468.                              (lookup_view_s, args, kwargs, len(patterns), patterns))

Exception Type: NoReverseMatch at /profiles/profile/maggie_s/
Exception Value: Reverse for 'auth_customuser_change' with arguments '(10001L,)' and keyword arguments '{}' not found. 0 pattern(s) tried: []

- [ ] Exception on submitting a video (/video/create/):

ImportError at /videos/create/
Missing amqplib library (pip install amqplib)
Request Method:	POST
Request URL:	http://unisubs.example.com:8000/en/videos/create/
Django Version:	1.7.11
Exception Type:	ImportError
Exception Value:	
Missing amqplib library (pip install amqplib)
Exception Location:	/usr/local/lib/python2.7/dist-packages/kombu/transport/amqplib.py in __init__, line 340
Traceback:
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response
  111.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py" in _wrapped_view
  21.                 return view_func(request, *args, **kwargs)
File "/opt/apps/amara/apps/videos/views.py" in create
  237.     if video_form.is_valid():
File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py" in is_valid
  162.         return self.is_bound and not bool(self.errors)
File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py" in errors
  154.             self.full_clean()
File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py" in full_clean
  354.         self._clean_form()
File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py" in _clean_form
  378.             cleaned_data = self.clean()
File "/opt/apps/amara/apps/videos/forms.py" in clean
  246.                 self.cleaned_data['video_url'], self.user)
File "/opt/apps/amara/apps/videos/models.py" in add
  747.         signals.video_added.send(sender=video, video_url=video_url)
File "/usr/local/lib/python2.7/dist-packages/django/dispatch/dispatcher.py" in send
  198.             response = receiver(signal=self, sender=sender, **named)
File "/opt/apps/amara/apps/videos/signalhandlers.py" in on_video_added
  52.     tasks.save_thumbnail_in_s3.delay(sender.pk)
File "/usr/local/lib/python2.7/dist-packages/celery/app/task.py" in delay
  461.         return self.apply_async(args, kwargs)
File "/usr/local/lib/python2.7/dist-packages/celery/app/task.py" in apply_async
  573.             **dict(self._get_exec_options(), **options)
File "/usr/local/lib/python2.7/dist-packages/celery/app/base.py" in send_task
  348.         with self.producer_or_acquire(producer) as P:
File "/usr/local/lib/python2.7/dist-packages/celery/utils/objects.py" in __enter__
  85.             *self.fb_args, **self.fb_kwargs
File "/usr/local/lib/python2.7/dist-packages/kombu/connection.py" in acquire
  883.                         R = self.prepare(R)
File "/usr/local/lib/python2.7/dist-packages/kombu/pools.py" in prepare
  61.             p = p()
File "/usr/local/lib/python2.7/dist-packages/kombu/utils/functional.py" in __call__
  29.         return self.evaluate()
File "/usr/local/lib/python2.7/dist-packages/kombu/utils/functional.py" in evaluate
  32.         return self._fun(*self._args, **self._kwargs)
File "/usr/local/lib/python2.7/dist-packages/kombu/pools.py" in create_producer
  41.         conn = self._acquire_connection()
File "/usr/local/lib/python2.7/dist-packages/kombu/pools.py" in _acquire_connection
  38.         return self.connections.acquire(block=True)
File "/usr/local/lib/python2.7/dist-packages/kombu/connection.py" in acquire
  883.                         R = self.prepare(R)
File "/usr/local/lib/python2.7/dist-packages/kombu/connection.py" in prepare
  1036.             resource = resource()
File "/usr/local/lib/python2.7/dist-packages/kombu/utils/functional.py" in __call__
  29.         return self.evaluate()
File "/usr/local/lib/python2.7/dist-packages/kombu/utils/functional.py" in evaluate
  32.         return self._fun(*self._args, **self._kwargs)
File "/usr/local/lib/python2.7/dist-packages/kombu/connection.py" in new
  1005.         return self.connection.clone()
File "/usr/local/lib/python2.7/dist-packages/kombu/connection.py" in clone
  539.         return self.__class__(**dict(self._info(resolve=False), **kwargs))
File "/usr/local/lib/python2.7/dist-packages/kombu/connection.py" in _info
  548.         D = self.transport.default_connection_params
File "/usr/local/lib/python2.7/dist-packages/kombu/connection.py" in transport
  784.             self._transport = self.create_transport()
File "/usr/local/lib/python2.7/dist-packages/kombu/connection.py" in create_transport
  527.         return self.get_transport_cls()(client=self)
File "/usr/local/lib/python2.7/dist-packages/kombu/transport/amqplib.py" in __init__
  340.             raise ImportError('Missing amqplib library (pip install amqplib)')

Exception Type: ImportError at /videos/create/
Exception Value: Missing amqplib library (pip install amqplib)


- [ ] Exception on saving subtitles from the editor:

app_1            | INFO 2018-03-01 08:23:02,856 teams.signals notification: subs-new (version: SubtitleVersion 1 / SjIWGVibW8zG / English v1)
app_1            | ERROR 2018-03-01 08:23:02,885 unhandled_error Missing amqplib library (pip install amqplib)
app_1            | Traceback (most recent call last):
app_1            |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
app_1            |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
app_1            |   File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
app_1            |     return view_func(*args, **kwargs)
app_1            |   File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 69, in view
app_1            |     return self.dispatch(request, *args, **kwargs)
app_1            |   File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 464, in dispatch
app_1            |     response = self.handle_exception(exc)
app_1            |   File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 461, in dispatch
app_1            |     response = handler(request, *args, **kwargs)
app_1            |   File "/usr/local/lib/python2.7/dist-packages/rest_framework/generics.py", line 192, in post
app_1            |     return self.create(request, *args, **kwargs)
app_1            |   File "/opt/apps/amara/apps/api/views/subtitles.py", line 861, in create
app_1            |     videos.tasks.video_changed_tasks.delay(video.pk)
app_1            |   File "/usr/local/lib/python2.7/dist-packages/celery/app/task.py", line 461, in delay
app_1            |     return self.apply_async(args, kwargs)
app_1            |   File "/usr/local/lib/python2.7/dist-packages/celery/app/task.py", line 573, in apply_async
app_1            |     **dict(self._get_exec_options(), **options)
app_1            |   File "/usr/local/lib/python2.7/dist-packages/celery/app/base.py", line 348, in send_task
app_1            |     with self.producer_or_acquire(producer) as P:
app_1            |   File "/usr/local/lib/python2.7/dist-packages/celery/utils/objects.py", line 85, in __enter__
app_1            |     *self.fb_args, **self.fb_kwargs
app_1            |   File "/usr/local/lib/python2.7/dist-packages/kombu/connection.py", line 883, in acquire
app_1            |     R = self.prepare(R)
app_1            |   File "/usr/local/lib/python2.7/dist-packages/kombu/pools.py", line 61, in prepare
app_1            |     p = p()
app_1            |   File "/usr/local/lib/python2.7/dist-packages/kombu/utils/functional.py", line 29, in __call__
app_1            |     return self.evaluate()
app_1            |   File "/usr/local/lib/python2.7/dist-packages/kombu/utils/functional.py", line 32, in evaluate
app_1            |     return self._fun(*self._args, **self._kwargs)
app_1            |   File "/usr/local/lib/python2.7/dist-packages/kombu/pools.py", line 41, in create_producer
app_1            |     conn = self._acquire_connection()
app_1            |   File "/usr/local/lib/python2.7/dist-packages/kombu/pools.py", line 38, in _acquire_connection
app_1            |     return self.connections.acquire(block=True)
app_1            |   File "/usr/local/lib/python2.7/dist-packages/kombu/connection.py", line 883, in acquire
app_1            |     R = self.prepare(R)
app_1            |   File "/usr/local/lib/python2.7/dist-packages/kombu/connection.py", line 1036, in prepare
app_1            |     resource = resource()
app_1            |   File "/usr/local/lib/python2.7/dist-packages/kombu/utils/functional.py", line 29, in __call__
app_1            |     return self.evaluate()
app_1            |   File "/usr/local/lib/python2.7/dist-packages/kombu/utils/functional.py", line 32, in evaluate
app_1            |     return self._fun(*self._args, **self._kwargs)
app_1            |   File "/usr/local/lib/python2.7/dist-packages/kombu/connection.py", line 1005, in new
app_1            |     return self.connection.clone()
app_1            |   File "/usr/local/lib/python2.7/dist-packages/kombu/connection.py", line 539, in clone
app_1            |     return self.__class__(**dict(self._info(resolve=False), **kwargs))
app_1            |   File "/usr/local/lib/python2.7/dist-packages/kombu/connection.py", line 548, in _info
app_1            |     D = self.transport.default_connection_params
app_1            |   File "/usr/local/lib/python2.7/dist-packages/kombu/connection.py", line 784, in transport
app_1            |     self._transport = self.create_transport()
app_1            |   File "/usr/local/lib/python2.7/dist-packages/kombu/connection.py", line 527, in create_transport
app_1            |     return self.get_transport_cls()(client=self)
app_1            |   File "/usr/local/lib/python2.7/dist-packages/kombu/transport/amqplib.py", line 340, in __init__
app_1            |     raise ImportError('Missing amqplib library (pip install amqplib)')
app_1            | ImportError: Missing amqplib library (pip install amqplib)
app_1            | INFO 2018-03-01 08:23:03,123 access POST /api/videos/SjIWGVibW8zG/languages/en/subtitles/ 500 (0.501s)

- [ ] Exception on sending a message:

ImportError at /messages/new/

Missing amqplib library (pip install amqplib)

Request Method: 	POST
Request URL: 	http://unisubs.example.com:8000/en/messages/new/
Django Version: 	1.7.11
Exception Type: 	ImportError
Exception Value: 	

Missing amqplib library (pip install amqplib)

Exception Location: 	/usr/local/lib/python2.7/dist-packages/kombu/transport/amqplib.py in __init__, line 340
Traceback:
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response
  111.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py" in _wrapped_view
  21.                 return view_func(request, *args, **kwargs)
File "/opt/apps/amara/utils/__init__.py" in wrapper
  54.             output = func(request, *args, **kw)
File "/opt/apps/amara/apps/messages/views.py" in new
  187.                 send_new_message_notification.delay(m.pk)
File "/usr/local/lib/python2.7/dist-packages/celery/app/task.py" in delay
  461.         return self.apply_async(args, kwargs)
File "/usr/local/lib/python2.7/dist-packages/celery/app/task.py" in apply_async
  573.             **dict(self._get_exec_options(), **options)
File "/usr/local/lib/python2.7/dist-packages/celery/app/base.py" in send_task
  348.         with self.producer_or_acquire(producer) as P:
File "/usr/local/lib/python2.7/dist-packages/celery/utils/objects.py" in __enter__
  85.             *self.fb_args, **self.fb_kwargs
File "/usr/local/lib/python2.7/dist-packages/kombu/connection.py" in acquire
  883.                         R = self.prepare(R)
File "/usr/local/lib/python2.7/dist-packages/kombu/pools.py" in prepare
  61.             p = p()
File "/usr/local/lib/python2.7/dist-packages/kombu/utils/functional.py" in __call__
  29.         return self.evaluate()
File "/usr/local/lib/python2.7/dist-packages/kombu/utils/functional.py" in evaluate
  32.         return self._fun(*self._args, **self._kwargs)
File "/usr/local/lib/python2.7/dist-packages/kombu/pools.py" in create_producer
  41.         conn = self._acquire_connection()
File "/usr/local/lib/python2.7/dist-packages/kombu/pools.py" in _acquire_connection
  38.         return self.connections.acquire(block=True)
File "/usr/local/lib/python2.7/dist-packages/kombu/connection.py" in acquire
  883.                         R = self.prepare(R)
File "/usr/local/lib/python2.7/dist-packages/kombu/connection.py" in prepare
  1036.             resource = resource()
File "/usr/local/lib/python2.7/dist-packages/kombu/utils/functional.py" in __call__
  29.         return self.evaluate()
File "/usr/local/lib/python2.7/dist-packages/kombu/utils/functional.py" in evaluate
  32.         return self._fun(*self._args, **self._kwargs)
File "/usr/local/lib/python2.7/dist-packages/kombu/connection.py" in new
  1005.         return self.connection.clone()
File "/usr/local/lib/python2.7/dist-packages/kombu/connection.py" in clone
  539.         return self.__class__(**dict(self._info(resolve=False), **kwargs))
File "/usr/local/lib/python2.7/dist-packages/kombu/connection.py" in _info
  548.         D = self.transport.default_connection_params
File "/usr/local/lib/python2.7/dist-packages/kombu/connection.py" in transport
  784.             self._transport = self.create_transport()
File "/usr/local/lib/python2.7/dist-packages/kombu/connection.py" in create_transport
  527.         return self.get_transport_cls()(client=self)
File "/usr/local/lib/python2.7/dist-packages/kombu/transport/amqplib.py" in __init__
  340.             raise ImportError('Missing amqplib library (pip install amqplib)')

Exception Type: ImportError at /messages/new/
Exception Value: Missing amqplib library (pip install amqplib)


- [ ] Exception on saving a team workflow:

ImportError at /teams/ted/settings/workflows/
Missing amqplib library (pip install amqplib)
Request Method:	POST
Request URL:	http://unisubs.example.com:8000/en/teams/ted/settings/workflows/
Django Version:	1.7.11
Exception Type:	ImportError
Exception Value:	
Missing amqplib library (pip install amqplib)
Exception Location:	/usr/local/lib/python2.7/dist-packages/kombu/transport/amqplib.py in __init__, line 340


- [ ] Exception on opening activity page for a new team:

EmptyPage at /teams/ted/activity/
That page number is less than 1
Request Method:	GET
Request URL:	http://unisubs.example.com:8000/en/teams/ted/activity/
Django Version:	1.7.11
Exception Type:	EmptyPage
Exception Value:	
That page number is less than 1
Exception Location:	/usr/local/lib/python2.7/dist-packages/django/core/paginator.py in validate_number, line 38
Traceback:
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response
  111.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/opt/apps/amara/apps/teams/new_views.py" in wrapper
  95.         return view_func(request, team, *args, **kwargs)
File "/opt/apps/amara/apps/teams/new_views.py" in activity
  675.     page = paginator.get_page(request)
File "/opt/apps/amara/utils/pagination.py" in get_page
  32.         self.add_links_to_page(page, request)
File "/opt/apps/amara/utils/pagination.py" in add_links_to_page
  39.             page.previous_page_number(), query)
File "/usr/local/lib/python2.7/dist-packages/django/core/paginator.py" in previous_page_number
  141.         return self.paginator.validate_number(self.number - 1)
File "/usr/local/lib/python2.7/dist-packages/django/core/paginator.py" in validate_number
  38.             raise EmptyPage('That page number is less than 1')

Exception Type: EmptyPage at /teams/ted/activity/
Exception Value: That page number is less than 1

**Comment by bendk** [comment]
I fixed the exception on the activity page, and also the ones related to the anonymous user.

For the other ones, I think you may need to run dev build again.

**Comment by PCF-Testing** [comment]
I am not sure what is going on, but I am still seeing the same exception on the user profile page.

I did the following things:
- git pull
- git submodule update
- bin/dev build
- bin/dev up
- bin/dev dbreset
- bin/dev manage createsuperuser

The user gets successfully created, but the activity page remains broken. Am I missing anything obvious here?

And I am still getting the same exception as before when attempting to submit a video. Building the app again has not resolved the issue. Is there anything else I could try?

**Comment by PCF-Testing** [comment]
So the user activity page seems to be partially fixed, at least for users with regular usernames. For Google OAuth users with @ in the username, the activity page (e.g. http://unisubs.example.com:8000/en/profiles/profile/pculture.qa%2540gmail.com/) 404s. For comparison, on production usernames with @ are escaped as %40, not %2540 - https://amara.org/en/profiles/profile/amara.test.1%40gmail.com/

The amqplib exception is still there (Missing amqplib library (pip install amqplib)) after dev build --no-cache.

**Comment by bendk** [comment]
I think the issue was on my end.  Just updated some things and now I think it should be working better.

**Comment by PCF-Testing** [comment]
The amqplib exception does not happen anymore.

- [ ] The user activity page raises the following exception:

EmptyPage at /profiles/profile/maggie_s/
That page number is less than 1
Request Method:	GET
Request URL:	http://unisubs.example.com:8000/en/profiles/profile/maggie_s/
Django Version:	1.7.11
Exception Type:	EmptyPage
Exception Value:	
That page number is less than 1
Exception Location:	/usr/local/lib/python2.7/dist-packages/django/core/paginator.py in validate_number, line 38

Traceback:
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response
  111.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/opt/apps/amara/apps/profiles/views.py" in profile
  110.                        extra_context=extra_context)
File "/opt/apps/amara/utils/objectlist.py" in object_list
  57.     return render(request, template_name, context)
File "/usr/local/lib/python2.7/dist-packages/django/shortcuts.py" in render
  50.     return HttpResponse(loader.render_to_string(*args, **kwargs),
File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py" in render_to_string
  178.         return t.render(context_instance)
File "/usr/local/lib/python2.7/dist-packages/django/template/base.py" in render
  148.             return self._render(context)
File "/usr/local/lib/python2.7/dist-packages/django/template/base.py" in _render
  142.         return self.nodelist.render(context)
File "/usr/local/lib/python2.7/dist-packages/django/template/base.py" in render
  844.                 bit = self.render_node(node, context)
File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py" in render_node
  80.             return node.render(context)
File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py" in render
  126.         return compiled_parent._render(context)
File "/usr/local/lib/python2.7/dist-packages/django/template/base.py" in _render
  142.         return self.nodelist.render(context)
File "/usr/local/lib/python2.7/dist-packages/django/template/base.py" in render
  844.                 bit = self.render_node(node, context)
File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py" in render_node
  80.             return node.render(context)
File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py" in render
  126.         return compiled_parent._render(context)
File "/usr/local/lib/python2.7/dist-packages/django/template/base.py" in _render
  142.         return self.nodelist.render(context)
File "/usr/local/lib/python2.7/dist-packages/django/template/base.py" in render
  844.                 bit = self.render_node(node, context)
File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py" in render_node
  80.             return node.render(context)
File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py" in render
  65.                 result = block.nodelist.render(context)
File "/usr/local/lib/python2.7/dist-packages/django/template/base.py" in render
  844.                 bit = self.render_node(node, context)
File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py" in render_node
  80.             return node.render(context)
File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py" in render
  65.                 result = block.nodelist.render(context)
File "/usr/local/lib/python2.7/dist-packages/django/template/base.py" in render
  844.                 bit = self.render_node(node, context)
File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py" in render_node
  80.             return node.render(context)
File "/usr/local/lib/python2.7/dist-packages/django/template/defaulttags.py" in render
  312.                 return nodelist.render(context)
File "/usr/local/lib/python2.7/dist-packages/django/template/base.py" in render
  844.                 bit = self.render_node(node, context)

- [ ] User activity pages for Google users (with @ in the username) and for users with non-ascii chars in the username 404.

- [ ] Unit tests produce several warnings:

/usr/local/lib/python2.7/dist-packages/djcelery/managers.py:77: RemovedInDjango18Warning: `ExtendedManager.get_query_set` method should be renamed `get_queryset`.
  class ExtendedManager(models.Manager):

/usr/local/lib/python2.7/dist-packages/djcelery/managers.py:108: RemovedInDjango18Warning: commit_manually is deprecated in favor of set_autocommit.
  @transaction.commit_manually

/usr/local/lib/python2.7/dist-packages/django/forms/widgets.py:143: RemovedInDjango18Warning: `TaskMonitor.queryset` method should be renamed `get_queryset`.
  .__new__(mcs, name, bases, attrs))

/usr/local/lib/python2.7/dist-packages/djcelery/admin.py:254: RemovedInDjango18Warning: Creating a ModelForm without either the 'fields' attribute or the 'exclude' attribute is deprecated - form PeriodicTaskForm needs updating
  class PeriodicTaskForm(forms.ModelForm):

/usr/local/lib/python2.7/dist-packages/django/forms/widgets.py:143: RemovedInDjango18Warning: `PeriodicTaskAdmin.queryset` method should be renamed `get_queryset`.
  .__new__(mcs, name, bases, attrs))

**Comment by bendk** [comment]
Those warnings are okay.  They from 3rd party modules, I think mostly celery related stuff.  The other issues should be fixed.

**Comment by PCF-Testing** [comment]
Tried dev manage migrate --fake, got the following during the migrations:

Running migrations:
  No migrations to apply.
  Your models have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
The following content types are stale and need to be deleted:

    auth | announcement
    auth | amaraapikey
    auth | emailconfirmation
    auth | sentmessagedate
    auth | customuser
    auth | awards
    auth | logintoken
    auth | userlanguage

Any objects related to these content types by a foreign key will also
be deleted. Are you sure you want to delete these content types?
If you're unsure, answer 'no'.

The following content types are stale and need to be deleted:

    notifications | teamnotificationsettings_extra_teams

Any objects related to these content types by a foreign key will also
be deleted. Are you sure you want to delete these content types?
If you're unsure, answer 'no'.

The following content types are stale and need to be deleted:

    videos | usertestresult

Any objects related to these content types by a foreign key will also
be deleted. Are you sure you want to delete these content types?
If you're unsure, answer 'no'.

The following content types are stale and need to be deleted:

    billing | billingtag

Any objects related to these content types by a foreign key will also
be deleted. Are you sure you want to delete these content types?
If you're unsure, answer 'no'.

I replied 'no' to all the prompts. Does this look correct?

**Comment by bendk** [comment]
You can reply yes, and that's what we'll be doing in production.  It should be fine.

**Comment by PCF-Testing** [comment]
Importing old DB route: exception on the team activity page

app_1            | ERROR 2018-03-08 08:54:43,287 unhandled_error global name 'contextq' is not defined
app_1            | Traceback (most recent call last):
app_1            |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
app_1            |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
app_1            |   File "/opt/apps/amara/apps/teams/new_views.py", line 95, in wrapper
app_1            |     return view_func(request, team, *args, **kwargs)
app_1            |   File "/opt/apps/amara/apps/teams/new_views.py", line 696, in activity
app_1            |     contextq['next_page_query'] = next_page_query.urlencode()
app_1            | NameError: global name 'contextq' is not defined
app_1            | INFO 2018-03-08 08:54:43,564 access GET /teams/ted/activity/ 500 (0.295s)

**Comment by bendk** [comment]
Fixed that one.

**Comment by PCF-Testing** [comment]
Verified.

**Comment by PCF-Testing** [comment]
Deployed.
