### ISSUE TITLE
rework team visibility, video visibility settings for new style teams

### ISSUE THREAD

**Issue by jdragojevic** [pculture/unisubs#2137]
Right now video visibility (is_visible; “videos public” in UI) setting + admission type setting implies team visibility.

Instead, we'll make this clearer on the Team Settings page.  Also, we'll add some new options:

**Heading:** visibility

**Admission type:** how they want people to find and join their team? 
- Dropdown - 
  - Invitation (optgroup) - new members must be invited.  You can choose who can invite:
    - Admins only (default)
    - Managers only
    - Anyone
  - Application - Users can apply to join, this needs to be approved by a team admin
  - Open - anyone can join
- The help label for the input gets dynamically updated based on the currently selected optoin

**Team visibility**
- Dropdown -   - Private (default): Only team members can see your team
  - Unlisted: Unlisted in the team directory.  However, users with a link to your landing page can view that page
  - Public: Listed in the team directory
- The help label for the input gets dynamically updated based on the currently selected optoin
 
**Video visibility** 
- Dropdown - helptext for currently selected option appears next to dropdown
  - Private (default): Videos can’t be viewed by the public
  - Public: Videos can be viewed by the public and appear in search results and on your landing page.
  - Unlisted: Videos can be viewed by the public if they have a link
- The help label for the input gets dynamically updated based on the currently selected optoin

Subtitle visibility/draft visibility will appear below these options pculture/amara-enterprise/issues/301

**Comment by jdragojevic** [comment]
heard from Darren who believes there are actual use cases for public invitation-only teams and private open teams.

- 1. Be Open, but want to keep all their videos private

USE CASE: Independent Film Maker that doesn't have time to approve applications or monitor team activity very much, but wants to have a semi-private space where it's likely that only interested translators will find the team and work on their film. Often times the team will be promoted via newsletters, blogs, or social media. Even though the layer of protection of someone random viewing their video for free is very thin, it's enough to give many of our clients comfort.

- 2. Be Invitation only, but want to have their videos public and editable

USE CASE: Colleges want this the most, from what I see. They want a place where students can view videos, but not allow them to translate or edit captioned. For a college admin to prompt students to create Amara usernames, apply to the team, and then approve those applications is too many steps to be attractive for this kind of use case.

**Comment by bendk** [comment]
The first step of this is going to be in gh-2137-prep.  In that branch we should:

 - [ ] Add 2 new fields on the team model: team_visibility and video_visilibity
 - [ ] Both fields should be present in the django admin form
 - [ ] For the team settings forms, and the API, you should still just see the is_visible field.  If you submit the form, we should also set the team_visibility and video_visibility settings

Everything else should work the same as before.

**Comment by bendk** [comment]
For the gh-2137-stage2 branch:

- [ ] we should do a data migration that sets team_visibility and video_visibility based on the is_visible field
- [ ] we should use team_visibility and video_visibility to to determine what's public and private.  is_visible should continue to be updated, but be ignored (you can test this by going in the django admin and manually changing team_visibility/video_visibility)

**Comment by bendk** [comment]
The gh-2137-stage3 branch should:
- [ ] change the new-style team settings form to display the new fields
- [ ] Also update the new-style team settings form based on pculutre/amara-entprise#301
- [ ] keep the old-style team settings form, and the team creation form the same
- [ ] update the API to accept both `is_visible` and `team_visibility`/`video_visibility.  If either `team_visibility` or `video_visibility` is present, then `is_visible` is ignored
- [ ] We should stop updating is_visible in all cases.

**Comment by bendk** [comment]
To do this one, I updated the settings page to use the futureui styles.  It's definitely a work in progress, I just wanted to get things working a bit.

**Comment by bendk** [comment]
Removed the part about doing pculture/amara-enterprise#301 alongside this one.  I'm realizing that one will take more work than I initially thought.

**Comment by PCF-Testing** [comment]
@bendk: there is one more branch, https://github.com/pculture/unisubs/tree/gh-2137-prep. What is it supposed to do? Should it be checked out, build and migrated before stage1? Does it require any checks?

**Comment by bendk** [comment]
gh-2137-prep was just left over from old code.  I just deleted it.

**Comment by PCF-Testing** [comment]
Got the following exception when running migrations on gh-2137-stage1:

Running migrations for teams:
 - Migrating forwards to 0152_auto__add_field_team_team_visibility__add_field_team_video_visibility.
 > teams:0152_auto__add_field_team_team_visibility__add_field_team_video_visibility
Traceback (most recent call last):
  File "/opt/apps/amara/manage.py", line 42, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 443, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 196, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 232, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/south/management/commands/migrate.py", line 107, in handle
    ignore_ghosts = ignore_ghosts,
  File "/usr/local/lib/python2.7/dist-packages/south/migration/__init__.py", line 219, in migrate_app
    success = migrator.migrate_many(target, workplan, database)
  File "/usr/local/lib/python2.7/dist-packages/south/migration/migrators.py", line 235, in migrate_many
    result = migrator.__class__.migrate_many(migrator, target, migrations, database)
  File "/usr/local/lib/python2.7/dist-packages/south/migration/migrators.py", line 310, in migrate_many
    result = self.migrate(migration, database)
  File "/usr/local/lib/python2.7/dist-packages/south/migration/migrators.py", line 133, in migrate
    result = self.run(migration)
  File "/usr/local/lib/python2.7/dist-packages/south/migration/migrators.py", line 106, in run
    dry_run.run_migration(migration)
  File "/usr/local/lib/python2.7/dist-packages/south/migration/migrators.py", line 191, in run_migration
    self._run_migration(migration)
  File "/usr/local/lib/python2.7/dist-packages/south/migration/migrators.py", line 178, in _run_migration
    raise exceptions.FailedDryRun(migration, sys.exc_info())
south.exceptions.FailedDryRun:  ! Error found during dry run of '0152_auto__add_field_team_team_visibility__add_field_team_video_visibility'! Aborting.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/south/migration/migrators.py", line 175, in _run_migration
    migration_function()
  File "/usr/local/lib/python2.7/dist-packages/south/migration/migrators.py", line 57, in <lambda>
    return (lambda: direction(orm))
  File "/opt/apps/amara/apps/teams/migrations/0152_auto__add_field_team_team_visibility__add_field_team_video_visibility.py", line 14, in forwards
    keep_default=False)
  File "/usr/local/lib/python2.7/dist-packages/south/db/generic.py", line 46, in _cache_clear
    return func(self, table, *args, **opts)
  File "/usr/local/lib/python2.7/dist-packages/south/db/generic.py", line 401, in add_column
    sql = self.column_sql(table_name, name, field)
  File "/usr/local/lib/python2.7/dist-packages/south/db/generic.py", line 689, in column_sql
    default = field.get_default()
  File "/opt/apps/amara/utils/enum.py", line 164, in get_default
    return self.default.number
AttributeError: 'int' object has no attribute 'number'

**Comment by bendk** [comment]
I think that one should be fixed.

**Comment by PCF-Testing** [comment]
Another exception in the same migration:

Running migrations for teams:
 - Migrating forwards to 0152_auto__add_field_team_team_visibility__add_field_team_video_visibility.
 > teams:0152_auto__add_field_team_team_visibility__add_field_team_video_visibility
Traceback (most recent call last):
  File "/opt/apps/amara/manage.py", line 42, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 443, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 196, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 232, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/south/management/commands/migrate.py", line 107, in handle
    ignore_ghosts = ignore_ghosts,
  File "/usr/local/lib/python2.7/dist-packages/south/migration/__init__.py", line 219, in migrate_app
    success = migrator.migrate_many(target, workplan, database)
  File "/usr/local/lib/python2.7/dist-packages/south/migration/migrators.py", line 235, in migrate_many
    result = migrator.__class__.migrate_many(migrator, target, migrations, database)
  File "/usr/local/lib/python2.7/dist-packages/south/migration/migrators.py", line 310, in migrate_many
    result = self.migrate(migration, database)
  File "/usr/local/lib/python2.7/dist-packages/south/migration/migrators.py", line 133, in migrate
    result = self.run(migration)
  File "/usr/local/lib/python2.7/dist-packages/south/migration/migrators.py", line 106, in run
    dry_run.run_migration(migration)
  File "/usr/local/lib/python2.7/dist-packages/south/migration/migrators.py", line 191, in run_migration
    self._run_migration(migration)
  File "/usr/local/lib/python2.7/dist-packages/south/migration/migrators.py", line 178, in _run_migration
    raise exceptions.FailedDryRun(migration, sys.exc_info())
south.exceptions.FailedDryRun:  ! Error found during dry run of '0152_auto__add_field_team_team_visibility__add_field_team_video_visibility'! Aborting.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/south/migration/migrators.py", line 175, in _run_migration
    migration_function()
  File "/usr/local/lib/python2.7/dist-packages/south/migration/migrators.py", line 57, in <lambda>
    return (lambda: direction(orm))
  File "/opt/apps/amara/apps/teams/migrations/0152_auto__add_field_team_team_visibility__add_field_team_video_visibility.py", line 14, in forwards
    keep_default=False)
  File "/usr/local/lib/python2.7/dist-packages/south/db/generic.py", line 46, in _cache_clear
    return func(self, table, *args, **opts)
  File "/usr/local/lib/python2.7/dist-packages/south/db/generic.py", line 401, in add_column
    sql = self.column_sql(table_name, name, field)
  File "/usr/local/lib/python2.7/dist-packages/south/db/generic.py", line 689, in column_sql
    default = field.get_default()
  File "/opt/apps/amara/utils/enum.py", line 163, in get_default
    if self.has_default() and isinstance(self.default.EnumMember):
AttributeError: 'int' object has no attribute 'EnumMember'

**Comment by bendk** [comment]
I think the second blind fix should work.

**Comment by PCF-Testing** [comment]
@bendk: I seem to be really stuck with migration to gh-2137-stage1. I have tried to do it in 2 different ways, which both keep failing:

1. From dev branch and a matching database:
docker-compose stop
docker-compose rm app worker queue
delete all *.pyc files
git checkout gh-2137-stage1
git submodule update
bin/dev build
bin/dev up
bin/dev manage migrate
Migrations freeze at 
Running migrations for teams:
 - Migrating forwards to 0152_auto__add_field_team_team_visibility__add_field_team_video_visibility.
 > teams:0152_auto__add_field_team_team_visibility__add_field_team_video_visibility

2. With full dbreset:
docker-compose stop
docker-compose rm app worker queue db
delete all *.pyc files
git checkout gh-2137-stage1
git submodule update
bin/dev build 
bin/dev dbreset
This fails with the error:
Traceback (most recent call last):
 File "/opt/apps/amara/manage.py", line 42, in <module>
   execute_from_command_line(sys.argv)
 File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 443, in execute_from_command_line
   utility.execute()
 File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 382, in execute
   self.fetch_command(subcommand).run_from_argv(self.argv)
 File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 196, in run_from_argv
   self.execute(*args, **options.__dict__)
 File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 231, in execute
   self.validate()
 File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 266, in validate
   num_errors = get_validation_errors(s, app)
 File "/usr/local/lib/python2.7/dist-packages/django/core/management/validation.py", line 103, in get_validation_errors
   connection.validation.validate_field(e, opts, f)
 File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/validation.py", line 14, in validate_field
   db_version = self.connection.get_server_version()
 File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/base.py", line 415, in get_server_version
   self.cursor().close()
 File "/usr/local/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 317, in cursor
   cursor = self.make_debug_cursor(self._cursor())
 File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/base.py", line 387, in _cursor
   self.connection = Database.connect(**kwargs)
 File "/usr/local/lib/python2.7/dist-packages/MySQLdb/__init__.py", line 81, in Connect
   return Connection(*args, **kwargs)
 File "/usr/local/lib/python2.7/dist-packages/MySQLdb/connections.py", line 193, in __init__
   super(Connection, self).__init__(*args, **kwargs2)
_mysql_exceptions.OperationalError: (1049, "Unknown database 'amara'")
repeated several times.
This error persists if I wait and retry, no matter how many retries. It remains there if I run docker-compose stop, docker-compose rm app worker queue db again.

Is there anything else I could try locally? Or, as a last resort, maybe we could set up a preview?

**Comment by PCF-Testing** [comment]
UPDATE: in method 1, when the app is stopped with a keyboard interrupt, the migration seemed to get "unstuck" and run to the end. Is there a sure way to check that all the migrations have run properly?

Dbshell displays the following structure for teams_team table:
mysql> show columns in teams_team;
+---------------------------------+---------------------+------+-----+---------+----------------+
| Field                           | Type                | Null | Key | Default | Extra          |
+---------------------------------+---------------------+------+-----+---------+----------------+
| id                              | int(11)             | NO   | PRI | NULL    | auto_increment |
| name                            | varchar(250)        | NO   | UNI | NULL    |                |
| slug                            | varchar(50)         | NO   | UNI | NULL    |                |
| description                     | longtext            | NO   |     | NULL    |                |
| logo                            | varchar(100)        | NO   |     | NULL    |                |
| square_logo                     | varchar(100)        | NO   |     | NULL    |                |
| is_visible                      | tinyint(1)          | NO   |     | NULL    |                |
| sync_metadata                   | tinyint(1)          | NO   |     | NULL    |                |
| points                          | int(11)             | NO   |     | NULL    |                |
| created                         | datetime            | NO   |     | NULL    |                |
| highlight                       | tinyint(1)          | NO   |     | NULL    |                |
| video_id                        | int(11)             | YES  | MUL | NULL    |                |
| application_text                | longtext            | NO   |     | NULL    |                |
| page_content                    | longtext            | NO   |     | NULL    |                |
| is_moderated                    | tinyint(1)          | NO   |     | NULL    |                |
| header_html_text                | longtext            | NO   |     | NULL    |                |
| last_notification_time          | datetime            | NO   |     | NULL    |                |
| notify_interval                 | varchar(1)          | NO   |     | NULL    |                |
| auth_provider_code              | varchar(24)         | NO   |     | NULL    |                |
| bill_to_id                      | int(11)             | YES  | MUL | NULL    |                |
| workflow_type                   | varchar(2)          | NO   |     | NULL    |                |
| projects_enabled                | tinyint(1)          | NO   |     | NULL    |                |
| workflow_enabled                | tinyint(1)          | NO   |     | NULL    |                |
| membership_policy               | int(11)             | NO   |     | NULL    |                |
| video_policy                    | int(11)             | NO   |     | NULL    |                |
| task_assign_policy              | int(11)             | NO   |     | NULL    |                |
| subtitle_policy                 | int(11)             | NO   |     | NULL    |                |
| translate_policy                | int(11)             | NO   |     | NULL    |                |
| max_tasks_per_member            | int(10) unsigned    | YES  |     | NULL    |                |
| task_expiration                 | int(10) unsigned    | YES  |     | NULL    |                |
| deleted                         | tinyint(1)          | NO   |     | NULL    |                |
| partner_id                      | int(11)             | YES  | MUL | NULL    |                |
| prevent_duplicate_public_videos | tinyint(1)          | NO   |     | 0       |                |
| team_visibility                 | tinyint(3) unsigned | NO   |     | NULL    |                |
| video_visibility                | tinyint(3) unsigned | NO   |     | NULL    |                |
+---------------------------------+---------------------+------+-----+---------+----------------+
35 rows in set (0.00 sec)

Django admin has the following fields:
![screenshot from 2017-12-14 04 21 39](https://user-images.githubusercontent.com/288455/33992140-5523ad02-e086-11e7-85e3-e830ba6d0192.png)

Are there any other hallmarks that could tell that the process that had not run gracefully was successfully completed?

**Comment by bendk** [comment]
That looks correct to me, I don't think you need to run any more migrations.

**Comment by PCF-Testing** [comment]
@bendk: I am not sure I fully understand the req's for stage 2.

First, changing team settings works one-way only - if I change the team visibility setting from the team settings page, this affects both is_visible flag and team_visibility setting. However, if I change the value of team_visibility from the django admin page, this only affects the status of the team on /teams/ and /teams/my/ pages, but not on the team settings page. Is this as expected?

Second, the value of "is_visible" parameter in the API Team resource does not seem to be determined by  "team_visibility" - if "team_visibility" is changed from "public" to "private" through django admin page, but "is_visible" remains checked, then the API call returns "is_visible": true.

Finally, if "team_visibility" is changed to "unlisted", /teams/ page tags this team as "Unlisted". Is this behaviour acceptable?

**Comment by PCF-Testing** [comment]
Also I have noticed that stage2 branch does not have "(private)" labels for private teams in the user profiles. For reference, on production these labels look as on the screenshot below:

![screenshot from 2017-12-15 05 53 58](https://user-images.githubusercontent.com/288455/34045160-a81c7ae4-e15c-11e7-8696-39afde5e3754.png)

**Comment by bendk** [comment]
> First, changing team settings works one-way only...

I think this is okay.  After stage2, we won't be using the old values anymore, so I don't think we need to keep updating them.

> Second, the value of "is_visible" parameter in the API Team resource does not seem to be determined by "team_visibility"

Yeah, after these changes, `is_visible` is not very  well definined.  I made it be based on the value of `videos_visible` instead of `team_visible`.  It should be exactly the same for old-style teams that only use the old forms.  For new-style teams that use the new forms, then there isn't any way to consistently return a true/false value there.

> Finally, if "team_visibility" is changed to "unlisted", /teams/ page tags this team as "Unlisted". Is this behaviour acceptable?

I think this is correct.  However, you should only see the team on that page if you're a member or a site admin.

> Also I have noticed that stage2 branch does not have "(private)" labels for private teams in the user profiles. For reference, on production these labels look as on the screenshot below:

This should be fixed now

**Comment by PCF-Testing** [comment]
@bendk: ok, I have a few more questions about stage2 branch:

- Should an **unlisted** team 404 when a non-member enters the url of the team UI page in the browser? If yes, this behaviour is inconsistent with the API, which returns 200 ok to non-members for /teams/[slug]

- Should a non-member be able to see the video page if video_visibility=private? (Currently the unauthorized viewer can open the video page, but not load the video player. Shouldn't the video page 403 or 404? It feels really strange when both team and its videos are private, but outsiders are allowed to see the video page, while team pages are all forbidden.)

- Video pages with video_visibility=unlisted behave like private ones - the video page and subtitle pages are visible to non-members, but the video player would not load. Is this the correct behaviour?

- Private and unlisted videos (video_visibility=private or unlisted) are included into the public profile of the user who submitted them, Videos tab, this feels like a bug.

- What should this mean: "Use video_visibility instead of is_visibile in the following places - what's listed on the team dashboard page"? Team dashboard or team landing page? Shouldn't team dashboard display all of the team's videos to the members of that team?

**Comment by bendk** [comment]
For the last one, yes I meant team landing page no the dashboard.  For the others, they were all bugs and my latest changes should fix them.

To make things work, I needed to change the embedder code, so can you test that I didn't break anything?

For the profile page, I changed it so you can only see private/unlisted videos if you're the user, or a superuser.

**Comment by PCF-Testing** [comment]
Confirming that most things have been fixed. One small thing is that private video pages in new (collab) teams are visible to anonymous (not signed in) users - shouldn't the page 403 in this case?

Team videos do not play in the embedder, no matter what permissions the user has. (Videos in the public space play just fine.) JS console says:
Uncaught TypeError: Cannot set property 'bg' of undefined
    at embedder.js:12386
    at Array.forEach (<anonymous>)
    at G.d.setFromVideoData (embedder.js:12385)
    at Object.success (embedder.js:12349)
    at l (embedder.js:39)
    at Object.fireWith [as resolveWith] (embedder.js:39)
    at T (embedder.js:39)
    at XMLHttpRequest.r (embedder.js:39)

**Comment by bendk** [comment]
Just pushed a fix for both of those issues.

**Comment by PCF-Testing** [comment]
The embedder on the language page with published subtitles should display subtitles in the language of the page by default, not in the primary language of the video. E.g., the embedder on http://unisubs.example.com:8000/en/videos/MiMV3DmROUZD/bg/210/?team=collab-test should have the Bulgarian subtitles selected by default, not English.

Example on production:
https://amara.org/en/videos/0fgF3tn9SNlX/zh-cn/1568908/?team=maggie-collab-test

Exception: the case when the language does not have any public version yet. In this case, the embedder is configured to display subtitles in the primary language or (if the transcript is also still private) any available published language.

**Comment by bendk** [comment]
I'm pretty sure that last issue was just because the embedder fix only worked on amara.org.  I updated the code so that it worked on dev instances as well.

**Comment by PCF-Testing** [comment]
gh-2137-stage3:

- [ ] "Publicly visible" is still present on the old team settings page, always is in OFF state

- [ ] Exception at creating a new team:
DatabaseError at /teams/create/
(1364, "Field 'is_visible' doesn't have a default value")
Request Method:	POST
Request URL:	http://unisubs.example.com:8000/en/teams/create/
Django Version:	1.4.22
Exception Type:	DatabaseError
Exception Value:	
(1364, "Field 'is_visible' doesn't have a default value")
Exception Location:	/usr/local/lib/python2.7/dist-packages/MySQLdb/connections.py in defaulterrorhandler, line 36
Python Executable:	/usr/local/bin/uwsgi
Python Version:	2.7.6
Traceback:
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response
  109.                         response = callback(request, *callback_args, **callback_kwargs)
File "/opt/apps/amara/utils/__init__.py" in wrapper
  55.             output = func(request, *args, **kw)
File "/opt/apps/amara/utils/decorators.py" in _checklogin
  41.             return view_func(request, *args, **kwargs)
File "/opt/apps/amara/apps/teams/views.py" in create
  204.             team = form.save(user)
File "/opt/apps/amara/apps/teams/forms.py" in save
  577.         team = super(CreateTeamForm, self).save()
File "/usr/local/lib/python2.7/dist-packages/django/forms/models.py" in save
  364.                              fail_message, commit, construct=False)
File "/usr/local/lib/python2.7/dist-packages/django/forms/models.py" in save_instance
  86.         instance.save()
File "/opt/apps/amara/apps/teams/models.py" in save
  321.         super(Team, self).save(*args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py" in save
  463.         self.save_base(using=using, force_insert=force_insert, force_update=force_update)
File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py" in save_base
  551.                 result = manager._insert([self], fields=fields, return_id=update_pk, using=using, raw=raw)
File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py" in _insert
  203.         return insert_query(self.model, objs, fields, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py" in insert_query
  1593.     return query.get_compiler(using=using).execute_sql(return_id)
File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py" in execute_sql
  912.             cursor.execute(sql, params)
File "/usr/local/lib/python2.7/dist-packages/django/db/backends/util.py" in execute
  40.             return self.cursor.execute(sql, params)
File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/base.py" in execute
  114.             return self.cursor.execute(query, args)
File "/usr/local/lib/python2.7/dist-packages/MySQLdb/cursors.py" in execute
  205.             self.errorhandler(self, exc, value)
File "/usr/local/lib/python2.7/dist-packages/MySQLdb/connections.py" in defaulterrorhandler
  36.     raise errorclass, errorvalue

Exception Type: DatabaseError at /teams/create/
Exception Value: (1364, "Field 'is_visible' doesn't have a default value")

**Comment by bendk** [comment]
Should be fixed now.  For the old-style team form, I think the plan is to keep the is_visible flag, and make it work like the API field.

**Comment by PCF-Testing** [comment]
On gh-2137-stage3 branch:

- [ ] In the API browser, Team Visibility and Video Visibility inputs are free text input, not drop-down selectors with the list of acceptable values. If an unexpected value is entered (e.g. "random" instead of "public"), an uncatched exception is raised.

- [ ] In the API call, if team_visible / videos_visible and is_visible flag have mutually exclusive values (example: "team_visible": "private", "videos_visible": "private", "is_visible": true), "is_visible" takes precedence. Is this the correct behaviour? From the overall context, it seems that starting from stage 3, team_visible and videos_visible should prevail over is_visible.

- [ ] Could the team settings page for new teams have an explanation on what the new fields and their values mean for teams? This is not intuitive and is likely to cause a lot of confusion if left unexplained.

- [ ] A unit test is broken on the branch:
======================================================================
ERROR: test_get_detail_checks_workflow_permissions (api.tests.test_videos.VideoViewSetTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/apps/amara/utils/test_utils/monkeypatch.py", line 245, in wrapper
    return func(self, mock_obj, *args, **kwargs)
  File "/opt/apps/amara/apps/api/tests/test_videos.py", line 561, in test_get_detail_checks_workflow_permissions
    self.viewset.get_object()
  File "/opt/apps/amara/apps/api/views/videos.py", line 659, in get_object
    raise http.Http404
Http404

**Comment by bendk** [comment]
>￼ In the API browser, Team Visibility and Video Visibility inputs are free text input, not drop-down selectors with the list of acceptable values. If an unexpected value is entered (e.g. "random" instead of "public"), an uncatched exception is raised.

I think the free text input is okay, since that matches what you'll need to do in code.  I fixed the exception though.

>  In the API call, if team_visible / videos_visible and is_visible flag have mutually exclusive values (example: "team_visible": "private", "videos_visible": "private", "is_visible": true), "is_visible" takes precedence. Is this the correct behaviour?

I think we should just call the behavior undefined.  If users are passing conflicting values then they're probably going to be surprised at the result no matter what.  I agree that the other behavior makes a bit more sense, but I don't want to commit to supporting this usage.

I added some help text to the team/visibility fields.  I tried to keep it short and to-the-point, hopefully it explains enough.

**Comment by PCF-Testing** [comment]
- [ ] Is this OK that on stage4 branch, Teams API resource still includes is_visible parameter, even though it is already removed from the database?

- [ ] For invitation-only teams, the branch has /teams/[team-slug]/admins/ page which lists the team admins' personal email addresses. It is a violation of Amara's privacy policy that forbids disclosure of users' email addresses. Instead, the page should have email (envelope) icons linking to Create Message page for the admin.

These seem to be the last issues in this ticket.

**Comment by PCF-Testing** [comment]
**NOTE for post-deployment:** when the change goes live, API documentation should be updated to reflect the changes. API clients should be notified about the changes.

**Comment by bendk** [comment]
>￼ Is this OK that on stage4 branch, Teams API resource still includes is_visible parameter, even though it is already removed from the database?

Yes we'll keep it there for a while for backward-compatibility purposes.

>￼ For invitation-only teams, the branch has /teams/[team-slug]/admins/ page which lists the team admins' personal email addresses. It is a violation of Amara's privacy policy that forbids disclosure of users' email addresses. Instead, the page should have email (envelope) icons linking to Create Message page for the admin.

This isn't from a code change in this branch.  I made #3081 for it.


> NOTE for post-deployment: when the change goes live, API documentation should be updated to reflect the changes. API clients should be notified about the changes.

Agreed on this one.  I don't think we need to go through the API freeze process, since the API is still backward compatible.  We should explain the new settings though and tell them that:
   - For new-style teams, they can start using the settings now
   - For old-style teams, I don't think the admin should have to think about the new settings.  They can set them via the API, but then if they go into the team settings page and save, then their work will be overridden.  Now that I think of it, I think we should remove the settings from the API for old-style teams because this is pretty confusing.

**Comment by bendk** [comment]
Talked about this on the devcall and we decided to remove the fields from the API for old-style teams.  Otherwise there's no clear thing we can tell them.

**Comment by bendk** [comment]
Just made a few changes to stage3:

 - For old-style teams, we no longer include the team_visibility or video_visibility fields in the API
 - We still include it for new style teams
 - We also still include it on the team listing API, and also allow it when creating teams via the API

**Comment by PCF-Testing** [comment]
On branch3, got an exception trying to create a team via API:
"type": "default",
"is_visible": false,
"team_visibility": unlisted,
"video_visibility":unlisted

DatabaseError at /api/teams/
(1364, "Field 'is_visible' doesn't have a default value")
Request Method:	POST
Request URL:	http://unisubs.example.com:8000/api/teams/
Django Version:	1.4.22
Exception Type:	DatabaseError
Exception Value:	
(1364, "Field 'is_visible' doesn't have a default value")
Exception Location:	/usr/local/lib/python2.7/dist-packages/MySQLdb/connections.py in defaulterrorhandler, line 36
Traceback:
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response
  109.                         response = callback(request, *callback_args, **callback_kwargs)
File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py" in wrapped_view
  77.         return view_func(*args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/rest_framework/viewsets.py" in view
  87.             return self.dispatch(request, *args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py" in dispatch
  464.             response = self.handle_exception(exc)
File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py" in dispatch
  461.             response = handler(request, *args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/rest_framework/mixins.py" in create
  21.         self.perform_create(serializer)
File "/opt/apps/amara/apps/api/views/teams.py" in perform_create
  659.         team = serializer.save()
File "/opt/apps/amara/apps/api/views/teams.py" in save
  604.         team = super(TeamSerializer, self).save()
File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py" in save
  175.             self.instance = self.create(validated_data)
File "/opt/apps/amara/apps/api/views/teams.py" in create
  615.         return super(TeamSerializer, self).create(validated_data)
File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py" in create
  827.             instance = ModelClass.objects.create(**validated_data)
File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py" in create
  137.         return self.get_query_set().create(**kwargs)
File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py" in create
  377.         obj.save(force_insert=True, using=self.db)
File "/opt/apps/amara/apps/teams/models.py" in save
  321.         super(Team, self).save(*args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py" in save
  463.         self.save_base(using=using, force_insert=force_insert, force_update=force_update)
File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py" in save_base
  551.                 result = manager._insert([self], fields=fields, return_id=update_pk, using=using, raw=raw)
File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py" in _insert
  203.         return insert_query(self.model, objs, fields, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py" in insert_query
  1593.     return query.get_compiler(using=using).execute_sql(return_id)
File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py" in execute_sql
  912.             cursor.execute(sql, params)
File "/usr/local/lib/python2.7/dist-packages/django/db/backends/util.py" in execute
  40.             return self.cursor.execute(sql, params)
File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/base.py" in execute
  114.             return self.cursor.execute(query, args)
File "/usr/local/lib/python2.7/dist-packages/MySQLdb/cursors.py" in execute
  205.             self.errorhandler(self, exc, value)
File "/usr/local/lib/python2.7/dist-packages/MySQLdb/connections.py" in defaulterrorhandler
  36.     raise errorclass, errorvalue

Exception Type: DatabaseError at /api/teams/
Exception Value: (1364, "Field 'is_visible' doesn't have a default value")

**Comment by bendk** [comment]
Did you run the migrations?  I'm pretty sure there's one that adds the default value.

**Comment by PCF-Testing** [comment]
I migrated back to teams 0154 before switching from stage 4 to stage 3 - it got stalled as most migrations in 2137. On stage3 branch, I ran manage/migrate, but that didn't seem to have taken any effect.

**Comment by bendk** [comment]
Ahh, so going backwards probably doesn't work correctly.  I would try going back to 0153, then forward again to 0154.

**Comment by PCF-Testing** [comment]
Migrating back to 0153 and then forward solved the problem. Migrations kept stalling, as usual, but after migrating back and forward the exception disappeared.

I think this ticket should be good to go now. Marking as Needs PR.

**Comment by bendk** [comment]
Starting the PRs now.  Just made one for stage1

**Comment by PCF-Testing** [comment]
http://amara.readthedocs.io/en/apidocs/api.html#teams needs updating.

**Comment by bendk** [comment]
The API is updated.  I'm going to merge 2137-stage4 into dev now.  I think we can close this one, but I'll leave that do you.

**Comment by PCF-Testing** [comment]
Deployed.
