### ISSUE TITLE
Activity log for moderated videos is overloaded with meaningless 'edited' entries

### ISSUE THREAD

**Issue by ehazlett** [pculture/unisubs#226]
For moderated videos, the activity log lists an 'edited' action every time a new version was created, which also happens when a draft is accepted or approved without any actual changes to the text. Is it possible to log only actual edits made to the subtitles?

**Comment by bendk** [comment]
I don't think this is still an issue.  If it is, can someone give an update and some more info on how we can start tackling it?

**Comment by PCF-Testing** [comment]
Still happens. On http://www.amara.org/en/teams/ted/activity/, you can see that edit entries come in pairs - it's a bug.

**Comment by bendk** [comment]
I believe this is fixed in the activity branch.

**Comment by PCF-Testing** [comment]
Verified that this does not happen anymore on the branch.

**Comment by PCF-Testing** [comment]
Still a problem on production after deploying activity branch - "edited" entries get duplicated: https://www.amara.org/en/teams/ted/activity/

This did not happen when testing locally. Possibly, an infrastructure issue?

**Comment by bendk** [comment]
We didn't deploy the activity branch yet.  It was the activity-prep branch.  We need to migrate the old activity entries before we can fully switch

**Comment by PCF-Testing** [comment]
Looks good on production after deploy.
