### ISSUE TITLE
Error in notification about editor's notes

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2436]
When another user leaves a note on your subtitles in the subtitle editor, the IM notification sent about it to the collaborator is broken - it contains HTML tags and an invalid link. The notification reads as follows:

{{ user's full name }} added a note while editing {{ video title }}

{{ user's full name }} added a note to subtitles on which you are collaborating. View tasks for <a href="http://www.amara.org/teams/ted/tasks/?team_video=206615&amp;assignee=anyone&amp;language_code=pl">Taiye Selasi: Don’t ask where I’m from, ask where I’m a local / Polish</a>.

<p> {{ Comment text }} </p>

The link should actually be:
http://www.amara.org/en/teams/ted/tasks/?lang=pl&team_video=206615&assignee=anyone

Example:
http://www.amara.org/en/messages/message/2774014
(recipient - ted_symbolt)

![screen shot 2015-12-14 at 13 21 05](https://cloud.githubusercontent.com/assets/288455/11801834/7a8d863a-a29e-11e5-9ce1-36cf0bba6c45.png)

Issue reported: 
http://ted-support.amara.org/helpdesk/tickets/82329

**Comment by bendk** [comment]
This one was pretty easy, I just pushed it directly to staging.  I also figured it would be easier to test there.

**Comment by PCF-Testing** [comment]
Not yet fixed. The language filter in the URL is fine now, but the messages still look broken, with HTML tags in them:

![editornotesnotificationsonstaging](https://cloud.githubusercontent.com/assets/288455/11912454/ddec2dfc-a5f1-11e5-9bd8-7b0ed041eb6c.png)

**Comment by bendk** [comment]
Hmm, yeah this one is harder.  I think we recently changed this so that you can't just send arbitrary HTML over the messaging system, since that allows any user to send another user potentially dangerous code.  I think there's a few potential solutions:

- Flag system messages and allow HTML in that
- Use an HTML sanitizer that allows only safe HTML through (this can be tricky though)
- Include only the URL in plaintext and have the messaging system automatically urlize it.

**Comment by PCF-Testing** [comment]
@bendk: I've got the impression that the only message type that has this issue is the one about notes made in subtitle editor. Hyperlinks in other notifications (such as applications to team, a new member in your team, or personal IM) look good - you can impersonate maggie_s on production and check http://www.amara.org/en/messages/ for examples. Maybe just something wrong with this particular template?

**Comment by bendk** [comment]
I believe the only links were links that we urlized ourselves -- aka links that we spelled out in plaintext, then we turned into URLs.  All other HTML code was escaped, which made these messages look bad (you also saw the `<p>` tag).

I pushed a fix to the gh-2436 branch that makes it so we don't escape system messages.  @PCF-Testing  does that fix the issue for you?  @syl22-00 does that seem like an okay thing to do?

**Comment by PCF-Testing** [comment]
This did not work too well for me. I tried in two different configurations, in a collab team and in TED-type task-based team.

For collab-based team, the message looked good and the link looked and functioned like a proper hyperlink, but the URL was wrong:

![editornotenotification](https://cloud.githubusercontent.com/assets/288455/13027396/3e36d0d0-d203-11e5-8006-abcbf6f0b6a5.png)

http://unisubs.example.com:8000/videos/mAA9bwJ8btGn/info/?tab=collaborations
The collab was actually a pro-request sent to a work team, so the video had no collaborations tab and the link redirected to the main video page instead of the collaborations page.

For the task-based team, the onsite notification about the editor's note did not arrive at all - only the email notification was delivered. There was also a problem with other system messages - about reviewing and accepting, approving and publishing the subtitles - which were also delivered only by email, but not into the inbox.

**Comment by bendk** [comment]
I fixed the collaboration link on the gh-unisubs-2436 branch on amara-enterprise.

I believe the issue you ran into with the notes was the same one I just ran into.  If the video title was long enough, then creating the note would overflow the subject field and cause an exception.  I fixed that issue by truncate the title.  Maybe we should increase the length to more than 100 chars as well.  200 would be more sensible IMHO.

**Comment by PCF-Testing** [comment]
Yes, that probably was the issue. Works now for me with the fix pulled in.

That still leaves a smaller issue with the link given in the notification. For a single-team collab, the URL redirects to the collaborations list for the video (/teams/team-slug/videos/video_id/collaborations/) instead of collaborations details where the text of the note is instantly visible (/teams/team-slug/videos/video_id/collaborations/language_code/). For cross-team collabs, where a collab and its video belong to different teams, the link following the above pattern just yields 404 - but would work well with the language code appended.

**Comment by bendk** [comment]
Makes sense, I just pushed a change for that on amara-enterprise.

**Comment by PCF-Testing** [comment]
Hmm, after the latest fix the link in "User added a note..." points to /messages/None - could you please take another look?

**Comment by bendk** [comment]
That should be fixed now.

**Comment by PCF-Testing** [comment]
Looks OK - making PR now.

**Comment by PCF-Testing** [comment]
Deployed.
