### ISSUE TITLE
Warn/prevent users from submitting a translation without a title/description

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#2540]
If a user submits a translation in the editor, that doesn't have a translated title/description we should warn them and prevent the action.  To be precice:

 - We should add a team setting for this.  What should the label be?
 - This should kick in when the user tries to submit any action -- except save-draft
 - If the video contains other metadata fields, should this apply to that as well?

**Comment by deanjansen** [comment]
Team setting: Require Title & Description Translation? Y/N

I'm following up with JZ to confirm the specifics of when this should kick in, but I think your assumption is correct.

Not for other fields, since something like name would often not be translated.

**Comment by deanjansen** [comment]
Setting Name: Require All Metadata Fields to be Translated - Y/N

1. Transcription / translation step: 
User cannot proceed if any metadata fields are blank.
They haven't opened the metadata editor. 
Show warning upon submission action.

2. Review / approval step: 
User cannot proceed if any metadata fields are blank.
They haven't opened the metadata editor 
Show warning upon submission action. 
(Assuming this will not impact admin's ability to do bulk approvals)

NOTE: Titles shouldn't pre-populate in the metadata editor. All metadata fields should start out blank until a user inputs text.

![screen_shot_2016-04-27_at_9 40 43_am](https://cloud.githubusercontent.com/assets/216145/14855085/5306c69a-0c60-11e6-80c5-6ecff91cb9c8.png)

**Comment by PCF-Testing** [comment]
Speaker names (which are actually enabled only for one project in one team)
should be filled out in the metadata pop-up, whether they are translated or
copied from the original without changes, so I think we should enforce that
one, too, when it is required.

**Comment by syl22-00** [comment]
This is done in gh-2540

Instead of a warning when user presses the publish button, the button is disabled, and a tooltip explains the reason. It seems to me to be more consistent with the behavior of the workflow panel, but can be changed.

The new team setting is `enable_require_translated_metadata`, when this setting key is present for the team, the translated metadata are required. Right now it can be added in the admin interface, do we need a checkbox to enable or disable it in the team settings?

**Comment by PCF-Testing** [comment]
The setting in the admin UI should be OK, IMO. To the best of my knowledge, only one team needs this feature.

With enable_require_translated_metadata on, I am seeing the video title copied into the field for the translated title and can submit a task without translating the metadata.

**Comment by syl22-00** [comment]
Issues should now be fixed:

* all actions that complete subtitles check for that new requirement
* speaker name also needs to be translated, if present
* title does not get pre-populated

**Comment by PCF-Testing** [comment]
- [ ] On the branch, the pop-up still gets pre-populated with the metadata:

![titledescriptionprepopulatedfields](https://cloud.githubusercontent.com/assets/288455/15091779/0db98230-1408-11e6-9460-8bf5431edd7f.png)

Steps to reproduce:
A. Submit a video, set the primary language, title, description and speaker name, then add it to TED / TEDTalks.
B. Add a transcript, review, approve and publish it.
C. Pick a translation task and open the pop-up for video title.

- [ ] The hint displayed on mouseover is not very visible and likely to get much attention from users. Is it hard to make a visible error message, similar to the ones shown when unsynced or blank subtitles are present? (If that is too hard/long to do, let's just skip it.)

![subtitlescannotbeblankerrormessage](https://cloud.githubusercontent.com/assets/288455/15091810/894e604a-1409-11e6-9124-5bc40616776a.png)

- [ ] In review and approve dialogs, "Approve" button is not grayed out when the translated metadata are missing - it is just unresponsive on clicking.

- [ ] Bulk approval still works when the translated metadata are missing. It shouldn't.

**Comment by syl22-00** [comment]
* I could not reproduce the first item, have you been using the latest code?
* I am not completely sure on the last item: I took out from the list of "bulk-approvable" tasks the ones that are missing title or description, is it what's expected?
* The other two items should now be fixed

**Comment by deanjansen** [comment]
My read of the feature request was to _not_ block bulk-approvals if the metadata was missing. Maggie, do you know for sure which way it was?

**Comment by syl22-00** [comment]
so I finally fixed the issue with the button in review mode that was not correctly disabled. Also reverted the bulk-approve changes. As discussed non-editor checks will be done in a separate ticket

**Comment by PCF-Testing** [comment]
1) If the video has no description, its translation is still required. It shouldn't when no description is available.

2) For collab-based teams with the translation of metadata required, an error message is displayed when a title or description is missing, but endorsing is still possible.

3) Several tests (all related to billing) fail on the branch.

**Comment by syl22-00** [comment]
For item 2. that's a good catch and comes from the fact that the "Endorse" action for collab teams have "complete=False". Is this a bug, or is there a reason for that?

**Comment by PCF-Testing** [comment]
@bendk: ^^

**Comment by bendk** [comment]
Yeah, checking for complete might not be the correct behavior.  For endorse, it's false because we don't want to flag the subtitles as complete until the final review/approval is complete.

So I think we need to try a different approach:
 - Check the action name.  Currently, I think only `send-back` and `save-draft` should be exempt from the check.
 - Add another flag on the action class.  Maybe we call it skip_translation_check or something.

**Comment by syl22-00** [comment]
Thanks @bendk I like your second solution.

**Comment by syl22-00** [comment]
Remaining issues have now been fixed:

* Description is now only required if setting is on and base decription is not empty.
* Following Ben's suggestion, there is a new parameter for actions that determines, for the teams that have it enabled, whether description of metadata are required. Only one action has the new setting different from the "complete" setting: endorse in case of collab team.
* Tests now pass as latest staging and master code was merged into the branch.

There is now a gh-unisubs-2450 branch in enterprise

**Comment by PCF-Testing** [comment]
Looks good.

**Comment by PCF-Testing** [comment]
Reminder: we'll need to configure the setting for TED on production when this feature goes live.

**Comment by PCF-Testing** [comment]
Deployed.
