### ISSUE TITLE
Subtitles not displayed on timeline at syncing step in FF/Linux

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2767]
Observed in the latest Mozilla Firefox (51) on Ubuntu.

Steps to reproduce:
1. Submit a video.
2. Open the subtitle editor to start a transcription.
3. Type several subtitles and start syncing them. Subtitle bubbles won't be displayed on the timeline.

**Comment by syl22-00** [comment]
@PCF-Testing I am on FF 51 on Linux and I can see the subtitles correctly in the timeline. Can you see anything in the console?

**Comment by PCF-Testing** [comment]
@syl22-00: have you tried updating the browser? This problem appears only with the latest changes. My configuration: whatismybrowser.com/w/9TDZSFK

Screenshot:
![subtitleeditorff51linux](https://cloud.githubusercontent.com/assets/288455/23155220/93d0343e-f7c6-11e6-9325-dd2bebc7fb12.png)

Console:
![consoleff51linux](https://cloud.githubusercontent.com/assets/288455/23155254/c31b4a6c-f7c6-11e6-900c-39f8ce9b3f5b.png)

**Comment by syl22-00** [comment]
@PCF-Testing Since I do not always see the issue I am not 100% sure that solved it, but it does not happen to me after a jQuery update which also solves a bunch of error messages. I pushed the changes in branch gh-unisubs-2767

**Comment by PCF-Testing** [comment]
I am still seeing the problem on the branch. Should I rebuild the app?

**Comment by syl22-00** [comment]
So I found a way to consistently reproduce, at least for me:

* Load the editor for new subtitles without the JavaScript console open
* Open the JavaScript console
* Enter one or a few subtitles
* Click to start syncing

If I have the JavaScript open when loading the editor, or if I do not open the console at all, I do not see the issue.

**Comment by syl22-00** [comment]
I think I finally understood the issue:
When the window is resized (for instance when opening the JavaScript console), Firefox does not update the CSS properties of hidden elements. In branch  gh-unisubs-2767-redo, I look at the value of the parent element in that case.

**Comment by PCF-Testing** [comment]
gh-unisubs-2767-redo fixes the issue.

**Comment by PCF-Testing** [comment]
Deployed.
