### ISSUE TITLE
"Amara respects your privacy" update on create autologin page

### ISSUE THREAD

**Issue by allison-amara** [pculture/unisubs#3135]
Login page > Sign In using existing identity > Google > choose account >

https://amara.org/en/auth/confirm_create/google/user@example.com/

![screenshot from 2018-04-12 01 54 31](https://user-images.githubusercontent.com/288455/38666753-907a358a-3df4-11e8-8203-84b3fbea271c.png)

The link with the text "Amara respects your privacy" takes me to http://pculture.org/pcf/websites-privacy/ which reads: 
Page Not Found 
Sorry, but the page you were trying to view does not exist.

it should go to: https://pculture.org/privacy

**Comment by kslottow** [comment]
This looks related to https://github.com/pculture/infrastructure/issues/121

**Comment by allison-amara** [comment]
@kslottow I cannot view the link you shared in your comment

**Comment by kslottow** [comment]
this works now, fixed in pculture/infrastructure#121

**Comment by PCF-Testing** [comment]
Still a problem. The link is outdated and needs replacement, should be https://pculture.org/privacy instead.

**Comment by bendk** [comment]
Made pculture/infrastructure#166 to also create a redirect for this.

**Comment by allison-amara** [comment]
This link still goes to https://pculture.org/pcf/privacy/ instead of https://pculture.org/privacy as of 9/25/2018

**Comment by bendk** [comment]
Just pushed a fix to dev.

**Comment by PCF-Testing** [comment]
Verified on dev.
