### ISSUE TITLE
Update reading speed in real time as start or end time for a subtitle changes

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#3228]
Steps to reproduce:

1. Open a synced set of subtitles for editing.
2. Click on a subtitle set to expose an info tray with the timing, character count, and reading speed info.
3. Seek to the subtitle.
4. On the timeline, drag the start or end time of the current subtitle.

Observed: the start or end time in the info tray changes as the subtitle edge is being dragged, but the reading speed does not change in the real time. It should.

https://pculture.freshdesk.com/a/tickets/102115
https://pculture.freshdesk.com/a/tickets/102118
https://support.amara.org/a/tickets/102120

**Comment by Rieann** [comment]
https://support.amara.org/helpdesk/tickets/102124 TED user

**Comment by bendk** [comment]
Fixed in the editor-fixes branch

**Comment by bendk** [comment]
This on was pretty high priority, so I cherry-picked it directly to production.

**Comment by PCF-Testing** [comment]
Sorry, still happening both on the branch and on production. The timestamps and reading speed in the info flyout do not get updated in real time as the subtitle edge is being dragged.

**Comment by bendk** [comment]
I thought this one was about the ! icon that displays next to the subtitle.  I can also fix the info flyout.

**Comment by bendk** [comment]
The other new issue is that for unsynced subtitles, when you start the drag you sometimes can get duplicate ones.

**Comment by PCF-Testing** [comment]
What is the scenario for dragging an untimed subtitle?

I am seeing a different problem on production - if a time change is undone with CTRL+Z, the info tray does not get updated accordingly. It should, both on Undo and Redo.

**Comment by bendk** [comment]
Actually the scenario above was dragging the subtitle being edited.  It didn't matter if it was synced or not.

I made #3230 for the ctrl-z issue.  Let's keep this one focused on the really bad issues that needed a hotfix.

**Comment by bendk** [comment]
I'm pretty sure this particular issue is now fixed on production.  There are a lot of side issues, I made #3233 for those.
