### ISSUE TITLE
Onsite messages to followers on subtitle updates are empty

### ISSUE THREAD

**Issue by ehazlett** [pculture/unisubs#621]
The onsite message to a follower reads:

[Subject:] New edits to "How to Speak Korean Like a Pro" by Maggie S on Amara

[Body: empty]

The message contains no links to the video and/or language.

At very least, the message should include links to the video view, subtitle view and editor's profile. It could also include a link to the diffing page between the last version and the previous version of the subtitles.

**Comment by PCF-Testing** [comment]
These messages are not being sent anymore.

**Comment by bendk** [comment]
I think the originial issue was fixed right?  Let's close this one and work on that one in #2593.

**Comment by PCF-Testing** [comment]
No, the original issue still remains, so reopening the ticket.
