### ISSUE TITLE
Application Pending message not updated after rejection

### ISSUE THREAD

**Issue by ehazlett** [pculture/unisubs#666]
Username PollyGlott applied to 'my-team' http://dev.universalsubtitles.org/en/teams/my-team/ on dev site.

Her application was rejected - yet on the teams page when logged in as that user, the application remained with a pending notice - even though the rejection message was received.

**Comment by kslottow** [comment]
I think this was fixed recently. @PCF-Testing can you check?

**Comment by PCF-Testing** [comment]
Yes, still happens as described for old-style teams.

For collab teams, "Your application has been submitted..." message gets removed once the application is rejected. After that, the user sees just a blank landing page, without "Apply to join" button or any message.

**Comment by kslottow** [comment]
ok, I don't think we should update for old style teams, but just checking that it is not a problem in new style teams. If it is still a problem in new style teams, please reopen
