### ISSUE TITLE
Combine VideoIndex and TeamVideoIndex into 1 search index

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#838]
They basically index exactly the same things, so we can save space and complexity by just having one index.

I think this would mean adding the following fields to VideoIndex:
* team_slug
* team_project_slug

Then we would need to change the Teams.models.get_videos_for_languages_haystack() method to use the video index instead of the TeamsVideoLanguageIndex.

**Comment by bendk** [comment]
Another idea for this would be to get rid of those indexes altogether and use mysql fulltext search for this functionality.  We could make a table that contained video_id and a text field that contained the text we are currently using for our document field on haystack.

I believe with django you can do a fulltext query with the normal model code, but you need to manually make the fulltext index.  That seems easier than maintaining haystack/solr as dependencies.

I think the first step would be to test creating this on staging and check if it works and it's fast enough.

**Comment by bendk** [comment]
When we handle this one, we may want to also tackle #2366

**Comment by bendk** [comment]
To implement this I needed to update the docker container for used for the database on our dev environments.  This means you need to recreate that container when switching to this branch and when switching back to staging.  Recreating the container means deleting all the data stored.  I would recommend using dbdump/dbload to avoid data loss.

Here's the commands I would use to switch branches:

```
dev dbdump backup.db
docker-compose stop
docker-compose rm db
git co gh-838 (or staging)
[in other terminal window] dev up
dev dbload backup.db 
```

**Comment by bendk** [comment]
This is implemented in the gh-838 branch (and also gh-unisubs-838 on amara-enterprise).

Couple of notes:
  - Make sure you restart your db instance as described above
  - Once you switch to the branch you'll need to re-index the existing videos using `dev manage index_videos --all`.  New videos and changes should cause reindexing automatically.
  - These pages need to be updated to use the new code, please make sure I didn't mess them up:
    - Video search / Featured videos / Latest videos
    - Team Videos (both old/new style
    - Move team videos on old-style teams
  - Only words with 3 or more letters are indexed.  Words that appear in over 50% of all videos will be ignored.

**Comment by bendk** [comment]
One more thing is that reindexing happens ever 10 seconds or so.  So if you do something like change the video description, there might be a slight lag before the search updates.  However, unlike before, this only applies to the search text, not other fields.  For example if you go to the team videos page, filter by project, then move some videos to another project, they should be excluded from the result set immediately.

**Comment by PCF-Testing** [comment]
1. When re-indexing videos with dev manage index_videos --all, hit the following error:

Traceback (most recent call last):
  File "manage.py", line 42, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 443, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 196, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 232, in execute
    output = self.handle(*args, **options)
  File "/opt/apps/unisubs/apps/videos/management/commands/index_videos.py", line 40, in handle
    VideoIndex.objects.index_videos(100)
  File "/opt/apps/unisubs/apps/videos/models.py", line 1120, in index_videos
    video.index.save()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 463, in save
    self.save_base(using=using, force_insert=force_insert, force_update=force_update)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 529, in save_base
    rows = manager.using(using).filter(pk=pk_val)._update(values)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 560, in _update
    return query.get_compiler(self.db).execute_sql(None)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 988, in execute_sql
    cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 818, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/util.py", line 40, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/base.py", line 114, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
django.db.utils.DatabaseError: (1406, "Data too long for column 'text' at row 1")

Some of the videos in the database did not get re-indexed and remained unsearchable. Refreshing the video metadata through Debug page did not help.

2. In new team UI, Edit button for individual videos does not seem to work anymore - the dialog would not be displayed on clicking the button.

3. Video search by multiple keywords seems to return data by either keyword (OR) rather than by all of them (AND). Example: when searching by "Brene Brown" (which is the full name of a TED speaker), the videos containing "Brene" or "brown" anywhere in the text are returned. I believe users would expect to find videos where both "Brene" and "Brown" would be present; if no match is found, users should try less detailed search.

**Comment by PCF-Testing** [comment]
NB: searching by language seems to work well with zh - zh-tw - zh-cn combination, so that bug seems to be fixed.

**Comment by bendk** [comment]
Okay, the 3 issues should be fixed.

I changed the migrate to fix the issue #1.  You may need to re-run the migration with:

```
  dev manage migrate videos 0172
  dev manage migrate videos 
```

To fix the issue with all terms being required, I switched to a boolean fulltext search.  I think that should do what we want, but it may not order the results properly.  We should double check that the matches are okay using the data on staging.  I'm not sure how important this is though.

**Comment by PCF-Testing** [comment]
Confirming the previous issues have been fixed.

However, now when searching in a collab-based team by a non-ascii keyword, e.g. "Brené Brown" (http://unisubs.example.com:8000/en/teams/ted-collab/videos/?q=Bren%C3%A9+Brown&project=&has_language=&missing_language=&sort=-time), I get the following error:

UnicodeEncodeError at /teams/ted-collab/videos/
'ascii' codec can't encode character u'\xe9' in position 4: ordinal not in range(128)
Request Method:	GET
Request URL:	http://unisubs.example.com:8000/en/teams/ted-collab/videos/?q=Bren%C3%A9+Brown&project=&has_language=&missing_language=&sort=-time
Django Version:	1.4.21
Exception Type:	UnicodeEncodeError
Exception Value:	
'ascii' codec can't encode character u'\xe9' in position 4: ordinal not in range(128)
Exception Location:	/opt/apps/unisubs/apps/videos/models.py in <genexpr>, line 157

Traceback:
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response
  109.                         response = callback(request, *callback_args, **callback_kwargs)
File "/opt/apps/unisubs/apps/teams/new_views.py" in wrapper
  101.             return view_func(request, team, *args, **kwargs)
File "/opt/apps/unisubs/apps/teams/new_views.py" in wrapper
  88.         return view_func(request, team, *args, **kwargs)
File "/opt/apps/unisubs/apps/teams/new_views.py" in videos
  306.     team_videos, filters_form = _videos_and_filters_form(request, team)
File "/opt/apps/unisubs/apps/teams/new_views.py" in _videos_and_filters_form
  292.         team_videos = filters_form.get_queryset()
File "/opt/apps/unisubs/apps/teams/forms.py" in get_queryset
  1042.             qs = qs.search(q)
File "/opt/apps/unisubs/apps/videos/models.py" in search
  157.         query = ' '.join('+"{}"'.format(t) for t in get_terms(query))
File "/opt/apps/unisubs/apps/videos/models.py" in <genexpr>
  157.         query = ' '.join('+"{}"'.format(t) for t in get_terms(query))

Exception Type: UnicodeEncodeError at /teams/ted-collab/videos/
Exception Value: 'ascii' codec can't encode character u'\xe9' in position 4: ordinal not in range(128)

**Comment by PCF-Testing** [comment]
Another quirk is that with the video titled "Shall We Dance Full Movie (2004)" (http://www.youtube.com/watch?v=n1s_4O4RQM4),  searching for "Dance" does return the expected result, while searching for "Shall We Dance" does not - normally, it should.

**Comment by bendk** [comment]
Looks lik ethat was an issue with how we handled quoting HTML entities.  I think it should be fixed in the branch now.

**Comment by PCF-Testing** [comment]
Still an issue on both counts. I have pulled in updates, killed the order worker app, cleaned up *.pyc files, restarted the dev instance and run the command that re-indexes the video - no improvements after that. Is there anything I might have missed?

**Comment by bendk** [comment]
I missed the issue with non-ascii chars.  It should be fixed in the branch.

I thought you were bringing up a different issue with the shall we dance example.  Before it wouldn't work to search `"shall we dance"` (with the quotes).  That got fixed with my earlier commit.  I also just fixed the issue with searching for `shall we dance` (no quotes).  Note that the word "we" is too short, and not indexed, so it's effectively the same as searching for `shall dance`

**Comment by bendk** [comment]
Also, you'll probably need to re-create the DB container to fix the searching issue.  I used the following commands:
```
dev dbdump db.backup
docker-compose stop db
docker-compose rm db
dev up (in another window)
dev dbload db.backup
```

**Comment by PCF-Testing** [comment]
OK, search seems to work fine now.

One last issue I have noticed is that videos from private teams (the ones with Videos public? checkbox cleared) are displayed on the latest/search pages and are searchable by anonymous and unauthorized users. This shouldn't happen - they must be listed only in their respective teams and be visible solely to team members.

**Comment by bendk** [comment]
That one should be fixed now.

**Comment by PCF-Testing** [comment]
In the latest version of the branch, the video privacy team setting is only respected for old-style teams. Videos from collab, ensemble, and simple teams that are supposed to be private, are still exposed on the Watch/Recent page.

**Comment by bendk** [comment]
How are you making them private?  If I go to the team settings page and uncheck `Videos public?`, then I don't see them anymore.  If I go to the workflow page and change the subtitle visibility to private, then I still see the videos.

This isn't very intuitive, and I think we have a ticket to improve the UI for this, but I think it's working correctly.

**Comment by PCF-Testing** [comment]
Just adding new videos to a team that has Videos public? checkbox cleared in the team settings.

**Comment by bendk** [comment]
Oops, I didn't test that one.  It should be fixed now.

**Comment by PCF-Testing** [comment]
Confirming the video privacy is fixed now.

However, on old teams the negative filter for subtitle language on the team videos page is broken again - the direct filter works correctly (e.g. http://unisubs.example.com:8000/en/teams/old-style/videos/?q=&project=any&lang-mode=%2B&lang=zh-cn&sort=-time returns the expected 2 videos, while http://unisubs.example.com:8000/en/teams/old-style/videos/?q=&project=any&lang-mode=-&lang=zh-cn&sort=-time returns all the videos in the same team, which is obviously wrong).

**Comment by PCF-Testing** [comment]
I think the feature in its current state is good enough to be merged to staging and re-tested against the data on staging.

One caveat: I noticed that exempting 2 or less character long words from the search index applies also to the Asian languages. Meanwhile, in Chinese or Japanese, a combination of two characters can make quite definite keyword. Example: 成龙 is the name of actor Jackie Chan (2 characters long). Would be really nice if we could include such combinations into the search index - maybe make an exception from 3+ chars rule for Chinese and Japanese characters, or check the length of slugified string for non-ASCII keywords. This can be isolated into a separate ticket though.

**Comment by PCF-Testing** [comment]
Deployed.

**Comment by bendk** [comment]
We've deployed the change that creates and updates this index, but the search code is still using the old index.  We need to deploy a second time.

**Comment by PCF-Testing** [comment]
Generally looks good on the local instance of staging, except for a migration issue with the use of an old DB. Search / indexing worked well.

**Comment by bendk** [comment]
I think this one is finally all complete.
